I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/act_2.rpy", line 255, in script
    finn "I believe that compromise will satisfy both worlds."
Exception: Sayer 'finn' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/act_2.rpy", line 255, in script
    finn "I believe that compromise will satisfy both worlds."
  File "/Applications/renpy-7.4.10-sdk/renpy/ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-7.4.10-sdk/renpy/ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'finn' is not defined.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.3.23091805
Winter Game Jam 2024 The Winter Rally 1.0
Mon Dec 30 21:35:35 2024
